// Predefined gemological vocabularies used for datalist autocomplete.
// Keeping these as guided suggestions (not hard constraints) allows custom
// values while keeping data clean enough for stats and filtering.

export const GEM_SPECIES = [
  "Corundum",
  "Beryl",
  "Diamond",
  "Garnet",
  "Tourmaline",
  "Spinel",
  "Chrysoberyl",
  "Quartz",
  "Opal",
  "Zoisite",
  "Topaz",
  "Peridot",
  "Zircon",
  "Feldspar",
  "Jade",
  "Lapis Lazuli",
  "Turquoise",
  "Pearl",
  "Amber",
  "Coral",
  "Malachite",
  "Pyrite",
  "Rhodonite",
  "Labradorite",
  "Iolite",
  "Apatite",
  "Sphene",
  "Demantoid",
  "Tsavorite",
];

export const GEM_VARIETIES: Record<string, string[]> = {
  Corundum: ["Sapphire", "Ruby", "Padparadscha", "Star Sapphire", "Star Ruby"],
  Beryl: ["Emerald", "Aquamarine", "Morganite", "Heliodor", "Goshenite", "Red Beryl"],
  Garnet: [
    "Almandine",
    "Pyrope",
    "Spessartine",
    "Grossular",
    "Tsavorite",
    "Demantoid",
    "Rhodolite",
    "Hessonite",
    "Malaya",
    "Color-Change Garnet",
    "Mandarin Garnet",
  ],
  Tourmaline: [
    "Indicolite",
    "Rubellite",
    "Paraiba",
    "Chrome Tourmaline",
    "Bi-Color",
    "Watermelon",
    "Verdelite",
    "Schorl",
  ],
  Chrysoberyl: ["Alexandrite", "Cat's Eye", "Yellow Chrysoberyl"],
  Quartz: [
    "Amethyst",
    "Citrine",
    "Ametrine",
    "Rose Quartz",
    "Smoky Quartz",
    "Rock Crystal",
    "Rutilated Quartz",
    "Tiger's Eye",
  ],
  Opal: ["White Opal", "Black Opal", "Fire Opal", "Boulder Opal", "Crystal Opal", "Matrix Opal"],
  Zoisite: ["Tanzanite", "Anyolite"],
  Topaz: ["Imperial Topaz", "Blue Topaz", "White Topaz", "Pink Topaz"],
  Feldspar: ["Moonstone", "Labradorite", "Sunstone", "Amazonite", "Spectrolite"],
  Jade: ["Jadeite", "Nephrite"],
  Spinel: ["Red Spinel", "Blue Spinel", "Pink Spinel", "Black Spinel"],
  Diamond: ["White Diamond", "Yellow Diamond", "Brown Diamond", "Pink Diamond", "Blue Diamond", "Green Diamond", "Black Diamond"],
};

// All varieties flattened for use when no species is selected
export const ALL_VARIETIES = Object.values(GEM_VARIETIES).flat();

export const GEM_COLORS = [
  "Colorless",
  "White",
  "Light Yellow",
  "Yellow",
  "Orange",
  "Padparadscha",
  "Salmon",
  "Light Pink",
  "Pink",
  "Hot Pink",
  "Red",
  "Purplish Red",
  "Light Purple",
  "Purple",
  "Violet",
  "Light Blue",
  "Blue",
  "Dark Blue",
  "Teal",
  "Light Green",
  "Green",
  "Dark Green",
  "Chrome Green",
  "Brown",
  "Golden",
  "Cognac",
  "Gray",
  "Black",
  "Multi-Color",
  "Parti-Color",
  "Color-Change",
];

export const GEM_CLARITIES = [
  "Loupe Clean",
  "Eye Clean",
  "Slightly Included (SI)",
  "Moderately Included (MI)",
  "Heavily Included (HI)",
  "Opaque",
];

export const GEM_CUTS = [
  "Round Brilliant",
  "Oval Brilliant",
  "Cushion Brilliant",
  "Cushion Mixed",
  "Emerald Cut",
  "Princess",
  "Pear",
  "Marquise",
  "Heart",
  "Radiant",
  "Asscher",
  "Step Cut",
  "Rose Cut",
  "Cabochon",
  "Briolette",
  "Faceted Freeform",
  "Carved",
];

export const GEM_SHAPES = [
  "Round",
  "Oval",
  "Cushion",
  "Square",
  "Rectangular",
  "Pear",
  "Marquise",
  "Heart",
  "Triangular",
  "Hexagonal",
  "Octagonal",
  "Freeform",
];

export const GEM_TREATMENTS = [
  "None",
  "Heat Treatment",
  "Fracture Filling",
  "Beryllium Diffusion",
  "Lattice Diffusion",
  "Flux Healing",
  "Irradiation",
  "Coating",
  "Oiling",
  "Resin Filling",
  "HPHT",
  "Laser Drilling",
  "Bleaching",
  "Unknown",
];
